### ISSUE TITLE
How to use this package well

### ISSUE THREAD

**Issue by alex0516** [brianlockwood/ForK#3]
Hi Brian,

Could you provide some documents which you referred to make this package. I mean where are the algorithms from. I found its a little hard to understand your codes and use them further. 

Cheers,
Alex

**Comment by brianlockwood** [comment]
Hi Alex,
This is a bit of an orphaned project from many years ago. The basics can all be found here:
http://www.gaussianprocess.org/

As for the derivative capability, you can find many articles on "Gradient Enhanced Kriging" that contain details for the method.

-Brian
